sudo: false
language: python
python:
    - "3.6"
install:
    - pip install python-coveralls
    - pip install -r requirements.txt
script:
    - flake8 --exclude=venv,setup.py --max-line-length=88
    - pytest
